### PR TITLE
make sites.js human-readable

### PR DESCRIPTION
**Pull request by dym-sh**
this PR re-implementes "commas-first" structre, first proposed and approved in #39
( https://github.com/XXIIVV/Webring/commit/3a75ddaf60ff22c567a4d84e958e912dcd1fe343#diff-eacf331f0ffc35d4b482f1d15a887d3b )

re-formated sites.js, to make it human-readable;
this will also make future editing (like adding site-types) simplier and clearer.

order and functionality stayed unchanged.

### CODE REVIEW

**Comment by ckipp01** [comment]
My personal preference is that we shouldn't do this. I know it used to be this way, and I really disliked it since it doesn't follow a standard "linting" practice. The way it is now, it can be run through Standard easily checked for single quotes, space between object brackets, and trailing commas. If we implement this, we can no longer do this.

If we are going to attempt to make this more easily readable, then I recommend that we put each key-value pair on its own line just like you did, but not with a leading comma unless we enforce that throughout the project, which I'd be against.

I'm much more in favor of this:
```
{ 
  url: 'https://electro.pizza',
  title: 'electro pizza',
  type: 'blog',
  author: 'rho',
  rss: 'https://electro.pizza/feed.xml',
  feed: 'https://electro.pizza/twtxt.txt'
}
```
rather than this:
```
, { url: 'https://electro.pizza'
    , title: 'electro pizza'
    , type: 'blog'
    , author: 'rho'
    , rss: 'https://electro.pizza/feed.xml'
    , feed: 'https://electro.pizza/twtxt.txt'
    }
```

**Comment by neauoire** [comment]
I'm pretty much ambivalent between the current format and a standard friendly unfolded display for readability.

```
{ 
  url: 'https://electro.pizza',
  title: 'electro pizza',
  type: 'blog',
  author: 'rho',
  rss: 'https://electro.pizza/feed.xml',
  feed: 'https://electro.pizza/twtxt.txt'
}
```

**Comment by dym-sh** [comment]
ok, now it's comma-lst

**Comment by dym-sh** [comment]
yeah, that's intentional, and officially acknowleged usecase: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

**Comment by dym-sh** [comment]
ok, no trailing commas

**Comment by ckipp01** [comment]
> yeah, that's intentional, and officially acknowleged usecase: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Trailing_commas

True, but the project is using Standard which [doesn't allow comma-dangle](https://standardjs.com/rules.html). Looks good though. Thanks!

**Pull request merged**
