### PR TITLE
Add jamesg.app to XXIIVV

### PR DESCRIPTION
**Pull request by jamesgoca**
I would like to submit my website for consideration to the XXIIVV webring.

Below is proof that I have added the XXIIVV logo to my site:

Screen Shot 2020-08-01 at 16 44 24

The above image links to the XXIIVV webring. Thank you for your time.

### CODE REVIEW

**Comment by jamesgoca** [comment]
My website is accessible at https://jamesg.app for your edification.

**Comment by neauoire** [comment]
Cool website, thank you for showing me the bandwidth conservation society.

**Comment by jamesgoca** [comment]
Thank you for your swift response! I submitted my website for consideration to the webring because I believe that design comes in all different forms. My personal aesthetic is that of doing things with less. Interestingly, your message reminded me that sometimes white and black isn't the only option. I can add new features to my site without compromising on my values of minimalism and bandwidth conservation.

To that end, I am making a few aesthetic changes. I'll be doing this slowly, but surely. My name is encoded in Morse in the background. There's a bit more color. The site feels more... alive.

Evidently, I made a typo in the link to my links page. The appropriate revision has been made.

I would love to be reconsidered for the webring. If you think my internet home is still not a good fit, no problem!

**Comment by neauoire** [comment]
Well, I'm curious to see where it will go. It's not really bland in the sense that it's lacking color, it's more in the sense that it has very limited personality and content, it feels like a resume more than someone's __corner of the internet__. I usually merge PRs from websites that have more than 3-4 pages.

**Comment by jamesgoca** [comment]
Thanks! I'm starting to slowly but surely add webpages. At present, I've created a page about my burgeoning passion for coffee. I'll see where it goes! I will submit my site for consideration again at some point. I love this webring!

**Pull request closed without merging**
