### PR TITLE
Adding myself to the webring

### PR DESCRIPTION
**Pull request by 0xroy**
Webring icon is located in the navbar

### CODE REVIEW

**Comment by 0xroy** [comment]
I also missed a comma, I just woke up ahah

Cheers

**Comment by ckipp01** [comment]
Hey, @0xroy another question! I noticed you had `fr` listed under the languages, but I don't see any French on your site. This is a new addition to the webring, and maybe not clear (I'll update the readme if that's the case), but the language key is for languages that are represented on your site. If you don't have any French on your site, I'd remove that from the language array. That way people who are filtering to find French sites won't include yours, which doesn't have French. If I missed the French portion of your site, ignore this!

**Comment by 0xroy** [comment]
I do speak French, but I thought that the parameter was not limited to the content and included contact, feed, wiki, etc.

I also included French because, even if unused, it’s still a networking parameter.

If it is limited to the content, I’ll remove it :)

**Comment by ckipp01** [comment]
I'd say yea, remove it for now. That field is only being used for the Portal portion of the website at the moment, which represents the content on your site. Sorry for the confusion on this!

**Comment by 0xroy** [comment]
Removed :)

Cheers!

**Comment by ckipp01** [comment]
Alright, a couple more things actually @0xroy. You Wiki and Hallway entries aren't showing up yet because there is a [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) issue. You'll need to allow this domain to access those resources. Let me know if you have any questions about this.

**Comment by 0xroy** [comment]
Mmmh, this is on the server level right? I’ll ask if it’s possible

**Comment by ckipp01** [comment]
Correct.

The files needs to be accessible via CORS, so for example if you're self-hosting, you need to make sure to allow the `webring.xxiivv.com` origin.

Here's an example of how to do so with Nginx:

```
location / {
    index index.html;
    if ($request_method = 'GET') {
        add_header 'Access-Control-Allow-Origin' 'https://webring.xxiivv.com';
        add_header 'Access-Control-Allow-Methods' 'GET';
        add_header 'Access-Control-Allow-Headers' 'DNT,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type,Range';
        add_header 'Access-Control-Expose-Headers' 'Content-Length,Content-Range';
     }
}
```

If you're hosting with someone else, you may need to just search how to do it or see if it's even possible (which it should be).

**Comment by ckipp01** [comment]
O, and one other thing. It looks like your ndtl file can't be found? Your site is returning a 404 when you try to fetch it.

**Comment by 0xroy** [comment]
https://github.com/XXIIVV/Webring/pull/324#issue-320713523

Fixed it here, simple file extension error, i’m not yet familiar with this format! `;` is the comment symbol right?

**Comment by ckipp01** [comment]
Cool, I see everything getting pulled in now correctly with the webring-cli. Once the cors stuff gets resolved you should see it show up in the hallway and wiki.

As for ndtl. If you didn't see it, @neauoire has some details [here](https://wiki.xxiivv.com/#indental) which talks a bit about it. Although, now that I look at it, it doesn't mention the `;` being a comment, but yes, it is.

**Pull request merged**
