### PR TITLE
Add amorris

### PR DESCRIPTION
**Pull request by AAorris**

### CODE REVIEW

**Comment by neauoire** [comment]
Welcome : )

**Comment by AAorris** [comment]
Thank you! :)

**Comment by neauoire** [comment]
You're missing an `author` parameter so you won't show up in the feed.

**Comment by AAorris** [comment]
Just noticed that. One sec.

**Comment by neauoire** [comment]
You need to use a tab, or 3 spaces between date and body

**Comment by neauoire** [comment]
that worked!

**Pull request merged**
