### PR TITLE
Added a bot index and a diary.

### PR DESCRIPTION
**Pull request by jimkang**
(Webring links are in footer of the pages.)

### CODE REVIEW

**Comment by jimkang** [comment]
Got it. I removed the weblog.

**Comment by neauoire** [comment]
Welcome aboard :)

**Comment by jimkang** [comment]
Hooray! Thanks for starting this.

**Comment by neauoire** [comment]
Glad to have you :) Looking forward to the new bots and projects.

If I may, I'd recommend you eventually change the URL to your blog, or a more general hub so one can discover your other projects.

**Comment by jimkang** [comment]
That is a good idea! I am actually gradually working toward a more general hub, but I don't have anything that's digestible yet. ([This](http://jimkang.com/observatory/) is intended to someday have a partially automated easy-to-read projects page.)

**Pull request merged**
