### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by cappyzeb**
http://freepages.rootsweb.com/~craigsplace/genealogy/01/rings/

### CODE REVIEW

**Comment by neauoire** [comment]
Hi Craig, that's a pretty interesting website you've got there.
Let me browse through a bit :)

**Comment by cappyzeb** [comment]
OH yeah, I like that part too.

**Comment by neauoire** [comment]
Your url is too long and breaks the page layout, I'll try to find a solution and merge this.

**Comment by wakest** [comment]
looks like they are also at the root of this domain http://www.balunsat.org

**Pull request closed without merging**
