### PR TITLE
Added My Link

### PR DESCRIPTION
**Pull request by UserUnknownX**
Thanks For making this Great website

[My link](https://userunknownx.github.io/)

### CODE REVIEW

**Comment by neauoire** [comment]
Hi, is it possible that the last update was from over a year and a half ago?

**Comment by UserUnknownX** [comment]
> Hi, is it possible that the last update was from over a year and a half ago?
> 
> Edit: I don't think it's a good candidate for the webring, the site looks like it's built on a general purpose framework and layout. We're trying to collect websites that are hand crafted, sorry.

Thanks for the reply, maybe my focus has been on learning my school work recently.

But I think the idea of this site is really good.

Maybe I will try to make a web site that are hand crafted,I didn't thought about it,thanks for your idea.

**Comment by neauoire** [comment]
Looking forward to see what you will make! Make another PR when you are ready :)
Good luck with your school work.

**Comment by UserUnknownX** [comment]
> Looking forward to see what you will make! Make another PR when you are ready :)
> Good luck with your school work.

But that should be in a few years I graduated from middle school, now I can't write with CSS what a good-looking website😂😂😂

**Pull request closed without merging**
