### PR TITLE
add gi.nseng.art

### PR DESCRIPTION
**Pull request by shrik3**
Hi,

I'd like to add https://gi.nseng.art to the webring :)  The webring icon is at the bottom.

### CODE REVIEW

**Comment by neauoire** [comment]
Very nice works! Currently the website is too bandwidth heavy for the webring, if you add lazy loading, or make thumbnails I'd be happy to merge it :)

**Comment by shrik3** [comment]
> Very nice works! Currently the website is too bandwidth heavy for the webring, if you add lazy loading, or make thumbnails I'd be happy to merge it :)

The images in the gallery view are "thumbnails", compressing them further causes distortion or pixelation (but I'll try to optimize this).

I added lazy loading attribute to images, does this suffice for now?

> \

**Comment by shrik3** [comment]
@neauoire ping

**Comment by neauoire** [comment]
Sorry I let this PR fall into oblivion, I've had a hard time keeping up with the webring this year :sob: The website loads instantly now, is this still something you'd like to be a member of despite my total mishandling of your application ^__^; I totally understand if you don't..

**Comment by shrik3** [comment]
Yes, please do add the site :)

> Sorry I let this PR fall into oblivion

Don't be sorry! I always appreciate your work maintaining this fine project.

P.S. I removed the webring logo after a while not receiving an update, I'll add it back!

**Comment by neauoire** [comment]
Welcome to the webring! And again, sorry. Your work is fantastic, it's nice to finally have a chance to see the whole pieces and not just the top half of them. Lemme know when the webring icon is back on if you can

**Comment by shrik3** [comment]
Thanks! 

> Lemme know when the webring icon is back on if you can

It's back now. As before, at the bottom.

**Pull request merged**
