### PR TITLE
Added batyshkaLenin to WebRing

### PR DESCRIPTION
**Pull request by batyshkaLenin**
12 pages: https://alexandr-sidorenko.me/sitemap-0.xml

### CODE REVIEW

**Comment by neauoire** [comment]
ss

- Not enough content, in the english version, blog is empty, and creativity has one post. 
- - All links in about send off-side

**Comment by batyshkaLenin** [comment]
image
Whoa! To be honest, I don't even know how to reproduce this...

**Comment by batyshkaLenin** [comment]
image
Even without javascript the page doesn't look like your screenshot

**Comment by batyshkaLenin** [comment]
What kind of browser is this?

**Comment by neauoire** [comment]
It's just netsurf, does your website need some sort of javascript to work?

**Pull request closed without merging**
