### PR TITLE
add https://brunolazzaro.com to the webring

### PR DESCRIPTION
**Pull request by brunolazzaro**
This is super cool. 👍

### CODE REVIEW

**Comment by brunolazzaro** [comment]
CloudFront will take an hour or two to propagate the changes to my site (Added the webring icon).

**Comment by neauoire** [comment]
Hi Bruno :)

I cannot find the content of your site wether it be a diary/portfolio/wiki. It just seems to be a page that sends to other social networks. The purpose of the webring is to encourage people to build a site hosting their own content. Let me know if there is a link I have not tried on your site.

**Comment by brunolazzaro** [comment]
Hey! The purpose of the sit is to be a diary / portfolio. Maybe I need to work on the copy? 'Stuff' is where I'm adding experiments and side projects and under that section a future "Latest Scribbles" will show up where I'm going to be doing some writing. I just finished re-working my site so content might be lacking atm. 

I'll submit a PR again in the future once, hopefully, has more content.

**Comment by neauoire** [comment]
Oh! So soon.games would be a good candidate. If you prefer to wait for the diary to be completed, no problem too. I'm looking forward to that next PR then, I will gladly merge it :)

**Pull request closed without merging**
