### PR TITLE
add pixouls.xyz

### PR DESCRIPTION
**Pull request by Pixouls**
howdy! the icon is located on the main index.html page

### CODE REVIEW

**Comment by neauoire** [comment]
I could find about 10 pages of content, but I couldn't find the about page?

**Comment by Pixouls** [comment]
@neauoire the "inspect composer" part of the index.html is what serves as my "about", would u prefer I made a separate page?

**Comment by neauoire** [comment]
Yes! I would :) That's the only thing missing before I can merge your PR.

**Comment by Pixouls** [comment]
Hmm okay I will think about how I want do that and update soon

**Comment by neauoire** [comment]
Welcome to the webring :) I'm glad you took the time to add an about page, it's perfect <3

**Pull request merged**
