### PR TITLE
added eli.li to sites.js

### PR DESCRIPTION
**Pull request by eli-oat**

### CODE REVIEW

**Comment by kodedninja** [comment]
Seems interesting. Warm welcome to the ring!

**Comment by ckipp01** [comment]
@kodedninja haha we must be on a similar schedule. I literally just sat down and was looking through this!

**Comment by kodedninja** [comment]
@ckipp01 haha sorry!

**Comment by ckipp01** [comment]
Hey! @eli-oat it looks like there is a CORS issue with fetching your feed for the hallway, which is why you aren't seeing your posts. If you're not sure how to fix it, you can see an example in the readme [here](https://github.com/XXIIVV/Webring#joining-the-hallway).

Let us know if you need any help!

**Comment by eli-oat** [comment]
Ah! I should have guessed as much. 

I’ll probs just migrate my twtxt file from tilde.town to my own domain to resolve this. 

Thanks so much for the heads up!

**Pull request merged**
