### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by Imperial-Industries**

### CODE REVIEW

**Comment by kodedninja** [comment]
The Webring icon is not a clickable link + please mention location of the icon in the pull request!

**Comment by Imperial-Industries** [comment]
What exactly do you mean?

**Comment by kodedninja** [comment]
Sorry, seems like it's some weird Safari issue. It works well in other browsers.

**Comment by Imperial-Industries** [comment]
Where should I write the location of the Webring?

**Comment by Imperial-Industries** [comment]
Oh ok. Thank you!

**Comment by kodedninja** [comment]
And "Submit a Pull Request with the location of the webring icon on your site". This means that in the description of the pull request you should describe the location of the Webring icon on your site, so the reviewer can find it easily.

To be honest I'm still unsure whether this site fits into the Webring, I'll ask for an opinion from @ckipp01.

**Comment by Imperial-Industries** [comment]
Ok, thank you

**Comment by Imperial-Industries** [comment]
Should I start a new pull request then?

**Comment by kodedninja** [comment]
No no, it's okay like this, don't worry! :D

**Comment by Imperial-Industries** [comment]
Thank You

**Comment by joshavanier** [comment]
I don't think this fits as this is most definitely not a hand-crafted website

**Comment by Imperial-Industries** [comment]
What do you mean by hand-crafted?

**Comment by joshavanier** [comment]
Like you designed and built it yourself, and not just used a template

**Comment by Imperial-Industries** [comment]
Oh ok. Well, may I keep the Webring on the page anyway, because this is a very cool concept?

**Comment by ckipp01** [comment]
Hey @Imperial-Industries, first off, I'm really glad that you made a personal site. That's great!

I'll have to agree with @kodedninja and @joshavanier though, and I don't believe your site to be the best fit for the webring. If you take a look at the [readme](https://github.com/XXIIVV/Webring/blob/master/README.md) you'll see a reference to the webring being a place for hand(self)-crafted websites, and it doesn't seem like your site really is one.

Again, I want to both commend you for having your own site, and encourage you to keep it up! If you get to a point where you decide to do a more customized site that you've built/designed, feel free to send another pr.

As for keeping the webring icon on your site, it's your site, so you are free to.

Cheers

**Pull request closed without merging**
