### PR TITLE
Update index.html with a new website

### PR DESCRIPTION
**Pull request by red47**
I added the webring icon on the index file. At the bottom.

### CODE REVIEW

**Comment by red47** [comment]
Wearing image is at the bottom of the index file

**Comment by neauoire** [comment]
Hi red47,

Your website in its current state is not a good candidate for the webring. I try to curate it with websites that have a bit more than a blog(more on the wiki side of things) but right now, the project page has blurbs but no project pages. I require websites to have at least 10ish topic pages that do not include blog posts.

**Comment by red47** [comment]
I understand, thank you.
in fairness, a lot of the sites on the webbing currently only have a page or two, if at all.

**Comment by neauoire** [comment]
I noticed, but during their application, they had each at least 10 topic pages. X(

**Pull request closed without merging**
