### PR TITLE
Add rodrigofranco.com

### PR DESCRIPTION
**Pull request by caffo**
HELLO WORLD

https://rodrigofranco.com/

Webring icon is in on the bottom right of every page.

### CODE REVIEW

**Comment by neauoire** [comment]
Nice website, I'm wondering, do you have any on-site projects? It seems like all the projects are documented offsite

**Comment by caffo** [comment]
Thanks. Most pages are for what I would call projects -- how I configure my vintage machines (x220), how do I manage my digital music library, vinyls, etc.

I would say the website is a simple wiki / ideas repository more than anything.

**Comment by caffo** [comment]
Moved some stuff around and now I have just 3 external links.

**Comment by neauoire** [comment]
I'm going to hold off merging this until there's more projects documented on the website itself, it's on track to getting there, but right now it feels incomplete. I hope you make another PR when the website is further down the line :)

**Comment by caffo** [comment]
@neauoire  I imported content from many of my other sites/sources and organized the homepage to make it clear. Sorry about being a pain, but I really think my site deserves to be part of the webring — I feel like I found my tribe there :)

Can I get reconsidered?  🙇

**Pull request closed without merging**
