### PR TITLE
added favicon

### PR DESCRIPTION
**Pull request by dym-sh**
[`favicon.ico`](https://raw.githubusercontent.com/dym-sh/Webring/master/favicon.ico) is acly 100x100 .png:

(renamed for backwards compatibility reasons)

### CODE REVIEW

**Comment by neauoire** [comment]
Could you make it all black instead of grey?

**Comment by dym-sh** [comment]
problem with just black or just white favicons is they barely if at all visible in several circumstances, like the bookmarks manager or dark-themed OS's

i'll make it black with white outline to account for both

**Comment by neauoire** [comment]
You could put it over a white fill

**Comment by dym-sh** [comment]
just white square looks less stylish

**Pull request merged**
