### PR TITLE
Add www.drawk.cab to the webring

### PR DESCRIPTION
**Pull request by drawk-cab**
Not sure about data-lang="en". The link isn't in any particular language. But the site is in English so I'm leaving it there.

### CODE REVIEW

**Comment by colourcountry** [comment]
Oh also sorry the image is a bit small. I'll fix that when I have more internet.

**Comment by colourcountry** [comment]
oh jeez i just realized i need to switch image depending on prefers-color-scheme. definitely a more internet problem

**Comment by drawk-cab** [comment]
Please let me know if the site doesn't fit the ring's vibe. I've enjoyed browsing through it and though my efforts are a bit scattershot I'd be honoured to be included.
Thanks!

**Comment by neauoire** [comment]
I'll have a second look today : )

**Comment by neauoire** [comment]
Hi!

Sorry for the extreme delay, I've been away from bandwidth for too long, I've had another look at your site today and I'm happy to bring it in to the webring, again, sorry for the long wait. Love your site :)

**Comment by drawk-cab** [comment]
Thanks :)

**Pull request merged**
