### PR TITLE
added magoz.is to sites

### PR DESCRIPTION
**Pull request by magoz**
I've added https://magoz.is :-)

### CODE REVIEW

**Comment by neauoire** [comment]
https://github.com/XXIIVV/webring#join-the-webring

**Comment by neauoire** [comment]
You could make it slightly smaller so it fits with the other 2 👍

**Comment by magoz** [comment]
> You could make it slightly smaller so it fits with the other 2 👍

🤔I think it's the cache. It should look like the screenshot:
screenshot 2018-12-24 at 21 14 02

**Comment by neauoire** [comment]
Ah! yes, it looks good now :)

**Pull request merged**
