### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Arty2**

### CODE REVIEW

**Comment by neauoire** [comment]
Welcome aboard! It's good to have you : )

**Comment by Arty2** [comment]
@neauoire I had this "make a webring" on my to-do for a while, very glad to be a part of this!

**Comment by neauoire** [comment]
Where is the ring button on your site btw, I can't find it : )

**Comment by neauoire** [comment]
ah! nvm, found it. Looks lovely 👍

**Pull request merged**
