### PR TITLE
Added azlen.me

### PR DESCRIPTION
**Pull request by azlen**
Webring icon is with other social media icons below my logo on the front page.

I am planning on also incorporating it into a footer so that it may appear on all pages and on mobile.

### CODE REVIEW

**Comment by kodedninja** [comment]
@azlen I wrote an email to the contact address you provided and it is not existing. Could you please include an address where we can contact you?

**Comment by azlen** [comment]
@kodedninja Thanks for the heads up, I had thought my email server had a catch-all route. Anyway, I have added the address now so it should work properly.

**Comment by ckipp01** [comment]
@azlen are you able to fix the merge conflict, and then we should be good to go!

**Comment by ckipp01** [comment]
Welcome to the ring!

**Comment by ckipp01** [comment]
Hey @azlen it looks like there is a CORS issue with trying to fetch your ndtl file for the wiki. You can find some info on the [README](https://github.com/XXIIVV/Webring#joining-the-hallway) on how to possibly fix it.

**Pull request merged**
