### PR TITLE
add foreverlikethis

### PR DESCRIPTION
**Pull request by jackeyjack1**
I believe my site meets the criteria sufficiently. Additionally, a unique aspect is the focus on webrings, link directories, blogrolls, niche search engines, etc. Let me know and all the best!

### CODE REVIEW

**Comment by jackeyjack1** [comment]
Forgot to include the location of the webring icon:
https://foreverliketh.is/#10-m-xxiivv-webring

**Comment by neauoire** [comment]
Hi again nyko :)

The website is still too much of a blog, too little customized from the default bear layout, and most of the pages are offsite links, and very little actual content of your own beside the drawings page. I feel bad closing the PR again because I can see you've started to add topics pages, but it's still not a good candidate for the webring. I'm not sure if you're still willing to try, but add some finessing to the website, make it feel unique, break away from the timeline/blog format and add art and document your interest, don't just link to them.

Good luck!

**Comment by neauoire** [comment]
Oups, wrong button

**Comment by neauoire** [comment]
Very nice website, I spent a long time going through your [forum post](https://forum.agoraroad.com/index.php?threads/the-personal-web.5647/), it's to see you pushing for a weirder more personal web, keep it up! Looking forward to watch your website grow

**Comment by jackeyjack1** [comment]
Thank you so much, means a lot and will do! 🙏

**Pull request merged**
