### PR TITLE
Add notes.neeasade.net

### PR DESCRIPTION
**Pull request by neeasade**
Hello,,

### CODE REVIEW

**Comment by neeasade** [comment]
Notes about this site: 

- it's meant to be wiki-ish, with edit history sorting order being the default
- it's all generated from emacs with org-mode markup
- there are 2 rss feeds, one full and one curated (I've linked the latter)
- Here's a few fun ones:
  - https://notes.neeasade.net/Automata-tiling-backgrounds.html
  - https://notes.neeasade.net/adhoc-executable-patching-on-nix.html

**Comment by neauoire** [comment]
Very nice looking site, I'll dig in. 
Are you a friend of @WesleyAC?

**Comment by neeasade** [comment]
I met @WesleyAC briefly @recursecenter, and I enjoy their thoughts and writing

**Comment by neauoire** [comment]
Everything look good! Welcome to the webring :)

**Comment by neeasade** [comment]
@neauoire thanks -- FWIW I've been an on and off follower of 100 rabbits over the past few years, thanks for sharing stuff, and I hope y'all are doin peachy.

**Pull request merged**
