### PR TITLE
Add nuel.pw

### PR DESCRIPTION
**Pull request by nuel**
Hey hey :) It's been a while. My website is back, new and improved. So I figured I'd request to join again.

I've added the webring icon to the About section. (Click on the nuel face.) It's a `details`/`summary` tag in disguise, so it's accessible without JavaScript.

I have also made a button to go with my entry.

Hope this is okay, let me know if I need to change anything!

### CODE REVIEW

**Comment by neauoire** [comment]
I'm currently away from reliable internet, if you leave your PR open,
I'll review it when I'm back to a wifi internet connection.

**Comment by nuel** [comment]
My bad! No rush and safe travels :)

**Comment by nuel** [comment]
Heya! Just a heads up that my link to the webring has now moved this page: https://nuel.pw/more.html
A little less obscure than just a random icon in the about section with no explanation. :)

**Comment by neauoire** [comment]
I love the new look, it had been a while since I last saw your website. It looks great! welcome to the webring :)

**Comment by nuel** [comment]
Aw, thanks <3 Good to be back!

**Pull request merged**
