### PR TITLE
Add breckyunits.com

### PR DESCRIPTION
**Pull request by breck7**
Webring location: https://breckyunits.com

### CODE REVIEW

**Comment by neauoire** [comment]
The page is too large for me to load at the moment, it's not a good candidate if I cannot review the site.

**Comment by breck7** [comment]
@neauoire what kind of computer are you using?

There's also a completely text version of every page. Just swap *.html with *.txt

https://breckyunits.com/index.txt

**Comment by breck7** [comment]
@neauoire can you provide some more details? this is the first complaint Ive ever gotten about the page being too large. Very curious to know whats going on.

**Comment by breck7** [comment]
@neauoire seriously the whole site shows 2 decades of blog posts. There is no script files, no analytics. There's a completely plain text version. The source code for every page is included. It has a unique homepage where you can see ~20 years of my thinking zoomed out (but you can zoom in as well).

Just because it is different, doesn't mean it is bad. Please give it some thought.

**Comment by neauoire** [comment]
Hi,

Yes sorry, I only just got back within reliable connectivity yesterday and I'll have a second look later today :)

**Comment by breck7** [comment]
Thank you @neauoire ! I really appreciate it. Perhaps there's a way I can better serve more limited devices. I do use CSS3 columns, the layout computations, might not be well optimized in older browsers. Or maybe I can further reduce image sizes. 

I appreciate the feedback.

**Comment by neauoire** [comment]
> @neauoire what kind of computer are you using?

It's a x230 thinkpad, running on satellite internet. Your website downloads some of the html and then just halts, I think my connection gives up before finishing the download and so I have an incomplete file, but I'm not sure, I haven't had that issue before except with very large pages. I use Netsurf as browser, so I don't see 3 layouts, just one and that's alright.

I'm wondering if maybe I haven't found a glitch in netsurf itself..

**Comment by breck7** [comment]
Ok, thanks for the info, I'll put it on my todo list to test with Netsurf.

**Pull request closed without merging**
