### PR TITLE
Update sites.js to be in compliance

### PR DESCRIPTION
**Pull request by streeetlamp**
Webring link is in the header of site, thanks. 
Sorry I did not see the notification of my removal from the webring, I have now made updates. Thank you

### CODE REVIEW

**Comment by ckipp01** [comment]
Hey @streeetlamp, thanks for addressing the webring icon.

Regardig #194 , one of the other things we had mentioned was it looked like your site may just be a copy of your tumblr activity, which would be in violation of the [webring criteria](https://github.com/XXIIVV/Webring#webring-criteria). Could you give us a bit more info on how the content on your site is curated? Does it just get generated from your Tumblr activity, or another way?

**Comment by kodedninja** [comment]
@ckipp01 as discussed earlier, I totally agree with you, but I'm also curious about the intent of the creator.

**Comment by neauoire** [comment]
I don't think it qualifies as a hand-crafted website, or a place to showcase the creator's audio/visual work.

**Comment by streeetlamp** [comment]
Once again sorry for the delay in responding. My site only uses tumblr as a host for content I curate for many reasons like particular interests and a shifting mood board that has been curated from content I have come across or created. I have designed the site and written the markup of the site. I could move content to a different platform if that changes opinions for some reason.

**Pull request closed without merging**
