### PR TITLE
+ Teknari :-)

### PR DESCRIPTION
**Pull request by teknari**

### CODE REVIEW

**Comment by neauoire** [comment]
Welcome aboard, it's an honour to have you :)

**Comment by joshavanier** [comment]
Webring link is missing. I think we should also consider adding warnings for NSFW content.

**Comment by neauoire** [comment]
I'm starting to think it would be nice to have a json object with some extra details, maybe like a title, author name and contact infos. Instead of displaying urls, we could display the site's `title`?

**Comment by ckipp01** [comment]
I would love to have an object with contact info such as an email. If that happened, I could build in an email function to the webring-checker so that if a site is down for more than like a week, it uses to contact info to shoot a message to the person notifying them (just in case they don't know).

**Comment by neauoire** [comment]
hey @ckipp01, how about something like [this](https://github.com/XXIIVV/Webring/blob/master/scripts/sites.js#L7)?

**Comment by ckipp01** [comment]
Yea, that would be totally fine!

**Comment by teknari** [comment]
Sorry about the Webring link. Will get right on that.

**Comment by teknari** [comment]
Link is up.

**Comment by neauoire** [comment]
Perfect! Thanks :)

**Pull request merged**
