### PR TITLE
refactored a bit

### PR DESCRIPTION
**Pull request by dym-sh**
sorry about that

/* i'll propose my url later on */

### CODE REVIEW

**Comment by neauoire** [comment]
I'm not too keen on merging refactoring PRs, unless it's adding new features or fixing something.
I mean, I could merge this, but this seems to only change the style of the code, I don't think it's necessarily making it faster. It might only going to make me less inclined to changing the codebase afterward.

**Comment by dym-sh** [comment]
yeah, i dont care either way just wanted to see css and inserted html more clearly

swapping `body > pre` for `main` was the biggest improvement w/o turning everything into vue+typescript probably

i also haven't touched the braces indents so thats nice i guess

you can close this np

**Comment by neauoire** [comment]
I'm not closing it right away, you're doing a few things in how I wish I did things. I'm trying to see what I can use now, in the hopes that I can code as neatly as this in the future.

**Comment by neauoire** [comment]
I'll keep the main container system, and I'll migrate the var to ES6 names for now.

**Comment by dym-sh** [comment]
if you wish to have the same level of es6++ knowledge and know-how, just work with a php stack with direct access to pure SQL queries from client side for a year so that evergreen browsers is your only escape
xDDddddd
:|

**Comment by neauoire** [comment]
I'm sorry to hear :/

**Pull request closed without merging**
