### PR TITLE
Add natehn.com to webring.

### PR DESCRIPTION
**Pull request by natehn**
Webring link and icon are in the lower right-hand corner. More artistic content coming to the site soon.

### CODE REVIEW

**Comment by neauoire** [comment]
It's a very good start but there isn't enough content to be a valid applicant to the ring. I noticed something, for the social icons, I think you're using a webfont which I can't see, or it failed to download so it left a few empty areas where the icon should have been, I'd suggest having some sort of fallback.

image

Anyhow, I like where this is going, it's up to you, you can leave this PR open while you work on the site and I can check it from time to time, or you can re-open a PR when there's more of of your works on the site.

Lemme know :)

**Comment by natehn** [comment]
Hi!

Thanks for your quick response, and thanks for pointing out the Font Awesome icon issue. Web design isn't my forte, but I will see what I can do! Could it potentially be caused some sort of content blocker on your system? 

I'll leave the PR open and follow up when I have more content. Probably a couple of months before I hit 10 pages - I wasn't sure how hard the line was :)

- Nathan

**Comment by neauoire** [comment]
The website is coming along nicely, if you'd like, I'd be willing to merge it if you're still interested.

**Comment by EdwinWenink** [comment]
Definitely enjoyed browsing your website for a bit :-)

**Comment by natehn** [comment]
Thanks! :) Yes, I'm still interested in joining the webring. Feel free to merge - and let me know if you need anything else from me!

**Comment by neauoire** [comment]
Could you resolve the conflict? I'll merge it after

**Comment by natehn** [comment]
Ah yes, sorry bout that. I just made a new pull request - https://github.com/XXIIVV/webring/pull/512

**Pull request closed without merging**
