### PR TITLE
Add seirdy.one

### PR DESCRIPTION
**Pull request by Seirdy**
Love this webring! The icon's at the bottom of the homepage. Once I
figure out nonces and resource fingerprint-based CSP exceptions I might
inline it.

### CODE REVIEW

**Comment by Seirdy** [comment]
Dark mode issue: looks like Webkit doesn't like inverting `<picture>` elements, at least if they contain SVGs. I'll fix it in a sec.

**Comment by neauoire** [comment]
Hey Rohan, it's good to see a pr from you. 
I can't find your works on your website at the moment tho? I can see your resume and 5s blogposts but no works/projects page or anything like it. In its current state your website does not qualify for the webring.

**Comment by Seirdy** [comment]
On Tue, Feb 02, 2021 at 07:14:55AM -0800, Devine Lu Linvega wrote:
>I can see your resume and 5s blogposts but no works/projects page or 
>anything like it.

Just added a "Projects" section to the "About" page. Currently has two 
entries; more coming soon™.

-- 
/Seirdy

**Comment by neauoire** [comment]
Let's keep this PR open until you have enough content for it to be merged :) I'm following you on masto, I'll keep an eye out for updates periodically.

**Comment by Seirdy** [comment]
On Wed, Feb 03, 2021 at 04:58:54PM -0800, Devine Lu Linvega wrote:
>Let's keep this PR open until you have enough content for it to be merged :)

Added 3 posts since, and force-pushed after rebasing on master. Should 
be up to the 10-page requirement by now (11 if the "Hello World" and 
music.txt get half-credit each).

-- 
/Seirdy

**Comment by neauoire** [comment]
Are you planning on making a sort of projects page? Or a place where you host some artistic content on the site itself? I normally don't count blog posts as pages in the context of the webring.

**Pull request closed without merging**
