### PR TITLE
add laeastra.com

### PR DESCRIPTION
**Pull request by laeastra**
https://laeastra.com/lae/

The webring icon is located at the bottom, above the footer.

### CODE REVIEW

**Comment by neauoire** [comment]
404

**Comment by laeastra** [comment]
@neauoire 
Sorry! The link was incorrect, this is the right one:

https://laeastra.com/lae/

**Comment by neauoire** [comment]
Wonderful :) I looooove your website, I'm honored to add it to the webring, welcome!
Looking forward to watch it grow.

**Comment by laeastra** [comment]
I'm the one who is very honored to be a part of the webring :) Thank you so much for the welcome!!

**Pull request merged**
