### PR TITLE
Add `giacintocarlucci.it` to webring

### PR DESCRIPTION
**Pull request by GiacintoCarlucci**
[giacintocarlucci.it][1] is a personal knowledge base where I like to share projects, blog posts and notes [2] about mostly everything new I can learn as a developer (with some extra arguments pages about my hobbies)[3]

I've added the webring icon on the right side of the footer.
The website is just HTML and a bunch of CSS lines, no Javascript.

[1]: https://www.giacintocarlucci.it
[2]: https://www.giacintocarlucci.it/docs/memex
[3]: https://www.giacintocarlucci.it/docs/photography

### CODE REVIEW

**Comment by EdwinWenink** [comment]
Cool site!

**Comment by GiacintoCarlucci** [comment]
Thank you @EdwinWenink! I've explored every link on the webring and I remember yours, the dark-mode GIF on the home page made me laugh so much that I added your website in my 'cool websites' list 😂

**Comment by EdwinWenink** [comment]
I didn't even see that! Such an honor :-D Glad you liked it.

**Comment by neauoire** [comment]
Nice website, I can't find where you share your projects tho, but it has a couple of nice pages.  

It looks a bit broken for me? Is this what it's supposed to like:
2021-11-26-173713_1366x768_scrot

**Comment by GiacintoCarlucci** [comment]
Well you're right, I don't have a 'projects' page as my blog posts are most of the time about some [projects](https://www.giacintocarlucci.it/docs/blog/2021-10-10_save-your-bonsai-with-arduino/) or [tutorials](https://www.giacintocarlucci.it/docs/blog/2020-20-03_the-xmlhttprequest-definitive-guide/), do you think I should have a 'projects' page?

Here's what is supposed to look like, tested in firefox and chrome, what browser are you using? (very clean one btw)

immagine

**Comment by neauoire** [comment]
Ah! that looks much better :)

I use netsurf, but while it's a bit messy, it's still totally navigable.

Welcome to the webring!

**Pull request merged**
