### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by florianporada**
Great project!
Would be happy to be part of the list :)

### CODE REVIEW

**Comment by neauoire** [comment]
Website looks all broken for me, and none of the links work.
Screenshot from 2020-05-22 05-50-19@2x

**Comment by florianporada** [comment]
Hmm that's odd. Which browser are you using?
I'll check what's going wrong there and open another PR once it's fixed.

**Comment by neauoire** [comment]
Using the latest firefox. Maybe I thought these were links because of the highlight state.

Screenshot from 2020-05-22 07-32-31@2x

**Comment by florianporada** [comment]
Got it. Thanks. :)
New pr coming soon.

**Pull request closed without merging**
