### PR TITLE
feat: add sxrekord.com to webring index

### PR DESCRIPTION
**Pull request by Crazyokd**
Hi, hoping to have my personal blog added to the webring index!
The webring icon can be found at the page:  [https://sxrekord.com/PY.html](https://sxrekord.com/PY.html)

### CODE REVIEW

**Comment by neauoire** [comment]
image

It looks a bit weird to me, is it normal that all I can see is just an orange frame?

**Comment by Crazyokd** [comment]
maybe you can try google chrome?

**Comment by neauoire** [comment]
Oh, it looks like it requires some heavy Javascript to display
properly. One of the rules of the webring is to have website that
doesn't need it to display the content.

I cannot install Chrome on this operating system, sorry.

**Comment by Crazyokd** [comment]
I just read the [README.md]() carefully and I'm sorry I can't join you

**Pull request closed without merging**
