### PR TITLE
adding ky.

### PR DESCRIPTION
**Pull request by RedactedProfile**

### CODE REVIEW

**Comment by RedactedProfile** [comment]
Hi

Just curious why I was rejected is all

Thanks

**Comment by neauoire** [comment]
Hi,

There are [3 rules](https://github.com/XXIIVV/webring#join-the-webring) to joining the webring, I reject PRs without descriptions for the applicant has not read the rules.

Here are the rules:

Add the webring icon to your website HTML.
    Add your website information to the [index.html](https://github.com/XXIIVV/webring/blob/main/index.html) file. Keep your link name short, and don't leave a trailing / in the href attribute. Use a sensible alphanumeric value for the id attribute.
    Submit a Pull Request with the location of the webring icon on your site. Pull requests with blank descriptions will be rejected.

**Comment by neauoire** [comment]
But having a look at your website and I think it is a bit too much on the blog side, and has very little actual information on your creative works, which are mostly documented offsite.

**Comment by RedactedProfile** [comment]
Oh! Interesting, I have no idea how the heck I missed that last part. I assure that I read the rules and did a number of changes to adhere to them, simple oversight.

I'm not terribly sure what's wrong with the blog format though. But if that's not a subjective style of website you'd like added to the ring, I suppose there's no point moving forward.

**Pull request closed without merging**
