### PR TITLE
Fix: Kae.si is now Nataziel.Nexus

### PR DESCRIPTION
**Pull request by awooff**
Hi!
My old domain expired sadly, so I don't have Kae.si anymore.
Nataziel.Nexus will be updated far more frequently now-

Mind if this gets updated here?
Thanks!

### CODE REVIEW

**Comment by neauoire** [comment]
For sure :) Merged, thanks for updating it.

**Comment by awooff** [comment]
Hiya! Just wondering, is there a reason my site isn't in the webring anymore? It fits all the requirements for the ring and such, and I've also given it an overhaul lately,

**Comment by neauoire** [comment]
No, that's weird. I remove websites periodically when they're offline for more than a month or two, but I don't remember removing yours.

Btw, I just checked and your website looks quite broken on firefox at the moment.


image

**Comment by awooff** [comment]
Oh dear god xD I have no idea what's gone on there. For some reason it loads fine for me though? I'll have to investigate before adding it back in a PR, thanks for letting me know lole. Sounds like a recent update I made with 11ty.
image

**Pull request merged**
