### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by harleykin**
I hope it's OK, I'm adding two sites: my personal blog and fansite for webrings.

Icon1: https://www.nickifaulk.com   (left sidebar under "Webrings!")
Icon2: https://fanlistings.nickifaulk.com/webrings   (right sidebar under "WebRings")

Thank you!  :)

### CODE REVIEW

**Comment by neauoire** [comment]
Just pick 1 url to add :)

**Comment by harleykin** [comment]
> 
> 
> Just pick 1 url to add :)

Understandable.  Updated to just the fanlisting URL, and removed image from my homepage.  Thanks!

**Comment by neauoire** [comment]
I don't think a portal to other webrings is a good candidate for this webring, sorry.

> The aim of the webring is to display hand-crafted personal websites showcasing the creator's audio, visual or written work.

**Comment by harleykin** [comment]
OK, you could have just said that in the beginning and I would have kept my personal domain.  It's not a portal or directory, it's a fansite dedicated to my love of webrings.

**Pull request closed without merging**
