### PR TITLE
add me.epidro.me

### PR DESCRIPTION
**Pull request by epidrome**
hi, thank you for the inspiration and the curation of this list

the icon has been placed at the bottom of the page

please note that the architecture of my site consists of
single pages placed in sub-domains bellow the main one
because different tools-workflows are used for each one.

### CODE REVIEW

**Comment by neauoire** [comment]
Not enough content, feel free to apply again when you have more pages in :)

**Comment by epidrome** [comment]
😕 🙄 

@neauoire have you checked the links at the bio (bottom of the page), where your logo is located?

e.g., the scholar.epidro.me link has about 100 web pages (20years of content)?

**Comment by neauoire** [comment]
Maybe the webring icon shouldn't be in `me.` in that case, there's very little invitation on that page to see the rest, there's a very proeminent github link, a few read links at the bottom, but it's not very clear that there's more.

The blog has 2 posts, maybe there are more? The design of the blog looks like a wordpress template, so I thought it was derelict. Also, it's under **Biographical note**, which doesn't make it very clear that it's where the rest of the website is located. I don't think it's a good candidate the webring in its current state, sorry.

**Comment by epidrome** [comment]
hi, thanks for the explanation

the link to the portfolio is at the bio under `scholar`
https://scholar.epidro.me/

**Pull request closed without merging**
