### PR TITLE
add colean.cc

### PR DESCRIPTION
**Pull request by threeoh6000**
The icon is in the footer.
I plan to add more informative pages to the website.

### CODE REVIEW

**Comment by neauoire** [comment]
Hi Celeste, 

Nice website, I'd love to have a look at your art and music, can you point me to where it is located on the site?

**Comment by threeoh6000** [comment]
I have added some under [this directory for art](https://colean.cc/art) and [this one for music](https://colean.cc/music)

I have some more music but I'd need to find it first.

**Comment by neauoire** [comment]
The website in its current state is lacking context for the art and music projects. But you're planning on adding more, so do you wanna keep this PR open so I can check it from time to time, or would you like to open a new one when the site is further down the line?

**Comment by threeoh6000** [comment]
I'll open one further down.

**Pull request closed without merging**
