### PR TITLE
Add Site

### PR DESCRIPTION
**Pull request by dan335**

### CODE REVIEW

**Comment by neauoire** [comment]
[Incomplete PR](https://github.com/XXIIVV/Webring#join-the-webring)

**Comment by dan335** [comment]
What's missing?  The webring icon is at http://danp.cc/

**Comment by neauoire** [comment]
- Submit a Pull Request **with the location of the webring icon** on your site.

**Comment by neauoire** [comment]
But also your site doesn't qualify for the webring.

**Single page websites, websites acting only as portals to other social platforms and websites will be rejected.**

The aim of the webring is to display hand-crafted personal websites showcasing the creator's audio, visual or written work. Your business site is probably not the best fit for the webring, and will be rejected.

**Pull request closed without merging**
