### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by soyboysky**
Hello! Im brand new to the whole wiki thing but i've great admiration for you guys! yall inspired my to make this website and i hope when i learn more about coding and HTML and all that jazz that i can integrate Riven into my site! until then, its all HTML.

### CODE REVIEW

**Comment by soyboysky** [comment]
i'm having trouble getting my page to show the svg file, but its there and linking. Do you have the webring logo in a PNG? it would be easier for me to implement a familiar file format.

**Comment by joshavanier** [comment]
SVG files are valid as `img` sources. You can also include the whole `<svg>...</svg>` tag in your page.

**Comment by soyboysky** [comment]
I got it!! thanks guys!

**Comment by neauoire** [comment]
Welcome aboard :)

**Pull request merged**
