### PR TITLE
_discovery

### PR DESCRIPTION
**Pull request by underscorediscovery**

### CODE REVIEW

**Comment by neauoire** [comment]
- Add the webring icon to your website html.
- Add your website url to the index.html
- Submit a Pull Request with the location of the webring icon on your site.

**Comment by underscorediscovery** [comment]
sorry, main page just said submit a PR. It was a link, I clicked it. 
Unclear there was more steps until viewing the information link / readme.
Will adjust

**Comment by neauoire** [comment]
np : )

**Comment by underscorediscovery** [comment]
done, see top of https://underscorediscovery.ca

**Comment by neauoire** [comment]
Welcome aboard :) 
It's good to have you!

**Pull request merged**
