### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by angadberar**
hello, 

I have made an attempt to add my web portfolio to the Webring. please advise.

location of webring icon - https://angadberar.xyz/Information

### CODE REVIEW

**Comment by neauoire** [comment]
image

Just looks like a white page for me? Does this require javascript to display anything?

**Comment by angadberar** [comment]
thats odd. I created the site on cargo. 
It might require javascript, however i am not completely sure

Please find the screenshot from my browser -
web_test

**Comment by neauoire** [comment]
I just checked, your website has this very strange bit of html for the body `'style="visibility: hidden;"'`, could you remove it?

**Comment by angadberar** [comment]
done, it was for .hover image 
Hope it works now?

**Comment by angadberar** [comment]
hey, hope its working now? let me know if i can provide any help help from here. 
thank you

**Comment by neauoire** [comment]
I've been running around a lot these past few days, I'll  test it first thing in the morning :)

**Comment by angadberar** [comment]
alright : )

**Comment by neauoire** [comment]
2021-11-25-181536_1366x768_scrot

Still a white page for me, the broken CSS stuff is gone, but I can't see the content for some reason :( Sorry, I'm not sure why.

**Comment by neauoire** [comment]
Oh no, wait, the style thing is still there in the body tag `visibility: hidden;`

**Comment by angadberar** [comment]
oh, this is odd. I don't understand why its showing a white screen. 
I tested the website on chrome, safari and firefox. 

Can we try the link 'angadberar.xyz' 
here the Webring link exists permanently on the footer. 

Thank you for your patience.
Would love to hear any suggestions from your end

**Comment by aadilayub** [comment]
I don't mean to be exclusivist, but as far as I can tell, [cargo.site](https://cargo.site/) is a site builder - whereas this webring has a strong focus on hosting *hand-crafted* sites, no? I always assumed the *hand-crafted* part meant hand-coded, as in written by the author using html or some other markup language, as opposed to using a site-building/hosting platform like webflow, squarespace, cargo, write.as, et cetera

**Comment by angadberar** [comment]
Hey aadil, 
thats a fair point. what do you suggest?

**Comment by neauoire** [comment]
Considering that you don't seem to have the controls to make it work without javascript due to the platform it's built with, I'd say that this website is not hand-made enough at this point. Sorry.

**Pull request closed without merging**
