### PR TITLE
Add malloc.dog

### PR DESCRIPTION
**Pull request by peixian**
Hello, been following for a hot second, love the ethos. Webring is with the nav bar. Cheers.

### CODE REVIEW

**Comment by neauoire** [comment]
Very nice website, the issue is that there are very few pages, I realize the tiddlywiki contains a lot(enough that it straight up crashes netsurf), but there's 3 projects on the site and some have [broken links](https://github.com/peixian/kevo-thesis/), and also they're documented offsite. I'm trying to collect websites for the webring that don't send to offsite pages and contain onsite documentation. 

Would you like to improve this and keep the PR opened while you make these changes?

**Comment by peixian** [comment]
Ah thanks for catching that, didn't even realize that repo was private. I'll change the projects to onsite documentation, been meaning to do that for a while anyways. I'll update this PR with another comment once I finish adding the onsite documentation. -- PeixianOn Nov 30, 2023, at 10:40 PM, Devine Lu Linvega ***@***.***> wrote:﻿
Very nice website, the issue is that there are very few pages, I realize the tiddlywiki contains a lot(enough that it straight up crashes netsurf), but there's 3 projects on the site and some have broken links, and also they're documented offsite. I'm trying to collect websites for the webring that don't send to offsite pages and contain onsite documentation.
Would you like to improve this and keep the PR opened while you make these changes?

**Comment by neauoire** [comment]
Keep me posted :)

**Comment by peixian** [comment]
@neauoire gave each of the project its own page with documentation hosted onsite. Let me know if there's anything else :)

**Comment by neauoire** [comment]
Thanks for improving the projects page :) Your site and works is excellent, looking forward to watching it grow. Welcome to the webring!

**Comment by iacore** [comment]
@peixian two things.

1. On https://webring.xxiivv.com/ you have two links. `class="rss"` is missing.
2. On your website you linked to https://webring.xxiivv.com/malloc. You should link to https://webring.xxiivv.com/#malloc instead.

**Comment by peixian** [comment]
@iacore ah thanks for catching that, will fix.

**Pull request merged**
