### PR TITLE
Add andrewchou.hashbase.io to sites

### PR DESCRIPTION
**Pull request by achou11**
Icon is located at the bottom of the page, in the sticky footer

image

### CODE REVIEW

**Comment by neauoire** [comment]
How do I enter the site?

**Comment by achou11** [comment]
Not sure what you mean. Am I missing something?

**Comment by achou11** [comment]
Also, just realized that the site technically violates the "no single-page" rule, so feel free to close this PR if you don't think it's a good fit and I'll remove the icon afterwards :)

**Comment by neauoire** [comment]
AAh yeah, I thought this was the entrance to the site.
If you ever decide to make yourself a personal website, feel free to apply again :)

**Comment by achou11** [comment]
Ah got it! Eventually will work on some stuff that'll be more appropriate :)

**Pull request closed without merging**
