### PR TITLE
Renamed URL for RSS and 88x31 assets

### PR DESCRIPTION
**Pull request by syxanash**
Renamed URL for assets RSS and 88x31 icon

### CODE REVIEW

**Comment by neauoire** [comment]
404 for me?
https://system31.simone.computer/assets/88x31.gif

**Comment by syxanash** [comment]
I've updated the DNS certificates an hour ago, so maybe still needs to propagate

**Comment by syxanash** [comment]
Just checked with a VPN outside of Europe is 404, looks like DNS propagation issue, I'll check again in a couple of hours

**Comment by neauoire** [comment]
Still 404

**Comment by syxanash** [comment]
I'm trying to resolve this with fly.io I think something broke in my DNS configuration, I'll open a new PR once I figure out what happened 👍  sorry again :(

**Comment by syxanash** [comment]
I've fixed my configuration, a DNS record was missing, could you let me know if it's reachable for you? I've been testing with different providers and it looks up

**Comment by syxanash** [comment]
Hey @neauoire is this ok to go in? I'm sure the issue has been resolved now 👍

**Comment by neauoire** [comment]
ah yes, sorry about that

**Pull request merged**
