### PR TITLE
Add link to my notebook site

### PR DESCRIPTION
**Pull request by ZoeB**
Hi!

My site's a sort of one-person-wiki that, amongst many other things, discusses music making workflows and offers guides to using various music making tools.

The webring icon's at the bottom-right, next to the other links in the footer, and looking stylishly cryptic.

What say you, yay or nay?

All the best!

### CODE REVIEW

**Comment by neauoire** [comment]
Hey Zoe,

I've just spent an hour going through all your notes!! Lots of amazing things in there, I'd love to add it to the webring, I have only one request, could you add an about link? I realize that there's a zoe blade page, but could you make a link to it from the top maybe with someway for me to contact you if the site goes down?

**Comment by ZoeB** [comment]
Yay, I'm glad you like the site!  I similarly clicked on a few others in the webring and got similarly sidetracked. 😄

Sure, I've now added an "About me" page, linked from the top of the sidebar on the left... complete with e-mail address.  How's that?

Cheers!

**Comment by neauoire** [comment]
Yep! That'll do! welcome to the webring zoe :>

**Comment by ZoeB** [comment]
Yay, thank you!

**Pull request merged**
