### PR TITLE
Add jzhao.xyz

### PR DESCRIPTION
**Pull request by jackyzha0**
Webring logo is bottom left on the website footer :'))

Such a wonderful group of websites, I always come back to this webring for inspo

### CODE REVIEW

**Comment by neauoire** [comment]
> Single page website, all projects are documented offsite.

**Comment by jackyzha0** [comment]
did you check https://jzhao.xyz/toc/directory/

**Comment by neauoire** [comment]
This should be the link that is used for the webring, it's a lot more in line with what the webring is for.
But even knowing about this page, I can't find a single link from the home page that will send me there?

**Comment by jackyzha0** [comment]
image
Each of these link to a page and there is an explicit link to that page in the second paragraph: 
image

**Comment by neauoire** [comment]
2021-12-05-171846_1366x768_scrot

I don't see the nodes at the back, I only see a few anchors and they point to the same page, I'm not sure how to get to what you see?

**Comment by jackyzha0** [comment]
> 2021-12-05-171846_1366x768_scrot
> 
> I don't see the nodes at the back, I only see a few anchors and they point to the same page, I'm not sure how to get to what you see?

Oh that's definitely not what it's supposed to look like haha. Do you have JS disabled?

**Comment by neauoire** [comment]
Yeah, one of the requirements for the webring is that the website be usable without javascript.

**Comment by jackyzha0** [comment]
ah I see. I'll delete the branch then!

**Pull request closed without merging**
