### PR TITLE
Added yhnck.xyz

### PR DESCRIPTION
**Pull request by yhancik**
The site is not finished (will it ever be?) but it fits the criteria for now ;)

### CODE REVIEW

**Comment by neauoire** [comment]
Hey yhancik!

Where is the about page?

**Comment by yhancik** [comment]
Ah damnit, missed that one. My homepage is pretty much my about page, though, I don't really have more to add than what I say there... mh 🤔

**Comment by yhancik** [comment]
@neauoire moved things around and there is now an about (mostly the website) page ;)
https://yhnck.xyz/about/

**Comment by yhancik** [comment]
Btw, should I add the curly braces around the name? I see most do, but some are missing it...

**Comment by neauoire** [comment]
No no, it's a CSS thing :)

Welcome to the webring!

**Pull request merged**
