### PR TITLE
Add richard-yang-chen.com to links space

### PR DESCRIPTION
**Pull request by YangIon**
Webring logo link is below menu button.

### CODE REVIEW

**Comment by neauoire** [comment]
Looks broken for me.
I couldn't find the content of your site.

**Comment by neauoire** [comment]
screen shot 2018-10-19 at 1 42 49 pm

**Comment by YangIon** [comment]
Sorry for the inconvenience! I recently restarted the project, but if you'd prefer a more completed version before adding the link I can just put in a pull request at a later date.

**Comment by neauoire** [comment]
Fair enough :)

**Pull request closed without merging**
