### PR TITLE
add in reference to the cli

### PR DESCRIPTION
**Pull request by ckipp01**
No hard feelings at all if you don't want this referenced in here, but I thought it'd be neat to also link the cli project for the webring that I made. I've got it to a point now where I feel like it's working really smoothly and should be able to mimic pretty much all the features of the webring.

### CODE REVIEW

**Comment by neauoire** [comment]
This was overdue, especially that I use it myself XD. 
Merged.

**Comment by ckipp01** [comment]
:grin: did you mean to merge it but close it instead @neauoire ?

**Comment by neauoire** [comment]
I'm not even awake yet.

**Comment by neauoire** [comment]
sorry XD

**Comment by ckipp01** [comment]
hahaha, no worries! Good morning!

**Pull request merged**
