### PR TITLE
[sites] adding dym.sh

### PR DESCRIPTION
**Pull request by dym-sh**
will finish within next couple hours, don't mind some 404s and such

webring icon with the link is bottom most on the right

### CODE REVIEW

**Comment by ckipp01** [comment]
Hey @dym-sh! Since you're still working on this and finishing some stuff up I'm going to wait to merge this. It looks like all the links in the /posts, /gallery, and /lab aren't leading anywhere yet. Also, I'm sure you're aware, but the /about takes you to the listing of the directory on your server rather than the page.

Just shoot us a message on here when everything gets cleaned up and is ready to go!

**Comment by neauoire** [comment]
Site is starting to look pretty good :)
There's a few broken images?

Screen Shot 2019-08-08 at 6 15 05 PM

**Comment by dym-sh** [comment]
going to fix and finish everything else this week, i happened to have less free time than i expected
i'll update on the status once it's done

**Comment by neauoire** [comment]
Can you fix the conflict? I'll merge.

**Comment by dym-sh** [comment]
oh.. i removed and re-forked that repo..
i'll make another PR

**Pull request closed without merging**
