### PR TITLE
Add kahpslock.dev

### PR DESCRIPTION
**Pull request by Kahppachino**
Will show up on all https://kahpslock.dev/ pages in the footer.

### CODE REVIEW

**Comment by neauoire** [comment]
Can't find clickable links, seems to require some sort of javascript thing to display home page.

**Comment by neauoire** [comment]
Oh, sorry, the yellow links are not done, I thought maybe it needed javascript or something for them to be clickable. Feel free to open an other PR when the website is further down the line :)

**Comment by Kahppachino** [comment]
The webring link is at the bottom left, not sure why it looks like that for you however?
image

**Comment by Kahppachino** [comment]
Apparently the site's animations are using JavaScript, which is why you were unable to see any content. I did not realize this, and will add a legacy JavaScript disabled version, I guess?

**Comment by neauoire** [comment]
Yes, that will help bring the site to validate with the basic [webring criterias](https://github.com/XXIIVV/webring#webring-criteria).

**Pull request closed without merging**
