### PR TITLE
add ribo.zone

### PR DESCRIPTION
**Pull request by ribozone**
Hello! I love so many of the sites on this webring and it'd be an honor to add my own: https://ribo.zone

The link I added to `index.html` is https://ribo.zone/neighborhood, my page dedicated to exploring handcrafted websites and where I put webring links. There's some javascript there to shuffle the entries on the page, but if you have it disabled, the XXIIVV webring should be in the top row.

### CODE REVIEW

**Comment by 0xsunil** [comment]
@ribozone Just here to comment that I really love your website. I visited it once via an [are.na](https://are.na) node and ended up writing a small piece in my personal journal. Thanks for bringing this beautiful site to life.

Sure, your website should be on the webring.

image

**Comment by ribozone** [comment]
@0xsunil Thank you for visiting my site and for the kind words!

**Comment by neauoire** [comment]
Wow, what a gorgeous website *__*!! 
Welcome to the webring <3

**Comment by ribozone** [comment]
Thank you so much!

**Pull request merged**
