### PR TITLE
Update sites.js

### PR DESCRIPTION
**Pull request by serocell**

### CODE REVIEW

**Comment by neauoire** [comment]
Incomplete.

**Comment by serocell** [comment]
now completed I think could you recheck, link added. unless it was some other factor.

**Comment by neauoire** [comment]
Could you also add a way to contact you in the `sites.js`

**Comment by neauoire** [comment]
I've merged this with the hope that you will add more pages, I could only find a single page that leads to third-party websites, which usually I do not merge. The goal is to get people to host their own content and maintain their website and documentation beyond a single page, either like a diary or a wiki.

I will check again in a week :)

**Comment by serocell** [comment]
I've opened the range of the site, and plan to continue to, but having
looked at the other sites I think I was in error in attempting to get
involved.

Apologies for any time wasted and I will remove the references to the
wearing from the site.

**Comment by neauoire** [comment]
If you expand your site further than a single-pager, we'd love to have you :)
Also, test your PR before submitting, to make sure that missing commas don't break the webring.

**Comment by serocell** [comment]
I think it's expanded as much as it it's going to be in the near future,
could you check it and let me know?

http://xxiii.co

**Comment by serocell** [comment]
shut this down just to tidy up didn't mean it in a negative way. still
interested in being involved, let me know once you've checked the site out.

**Pull request merged**
