### PR TITLE
Adding my site to the ring

### PR DESCRIPTION
**Pull request by jalcine**
Right now, the ring icon is at the bottom of the page. I'm planning to move it (and my other member rings) up next to my search region (to promote that more)

### CODE REVIEW

**Comment by neauoire** [comment]
Hey jalcine! it's nice to see a PR from you, I've been following your works for a while. Could you edit your PR to link to the home instead of the about page?

**Comment by jalcine** [comment]
Hey! You as well! And no problem!

(Originally published at: https://jacky.wtf/2022/4/Dl/Dl1ab4MDC6mR0vBU40r_as8_)

**Comment by neauoire** [comment]
Right now, most of your website is your microblog, but do you have projects and pages that are documented on your website itself, and not on 3rd party sites? I need to about 10 content pages for the website to be valid for the webring.

The articles pages give me:

image

**Comment by jalcine** [comment]
Hm, I hadn't fleshed those parts out yet (they're meant to be a 'content channel'). Do you mind if I come back with a ping when I confirm that I have pages that match these requirements?

(Originally published at: https://jacky.wtf/2022/4/mg/mg1TT-SDSM5gAjUWBisdFyxj)

**Comment by neauoire** [comment]
Sure :) We can keep this PR open, or you can open another one when the site is ready.

**Pull request closed without merging**
