### PR TITLE
Add personal website to index.html.

### PR DESCRIPTION
**Pull request by jo185**
@neauoire please review the file and if everything is ok with index.html as well as wit my site, add me to this list of magical web creations.

Thanks a lot, Jo<3

### CODE REVIEW

**Comment by jo185** [comment]
Oh i forgot! The webring icon is on the bottom left of the homepage.

**Comment by neauoire** [comment]
Hi :) Thank you for applying to the webring. The website is a bit bare right now, I can only find 2 or 3 pages is there a way to go deeper into the site that I'm not seeing?

Side note: Your images are pretty heavy, even tho they display quite small, they are not optimized for web and some are pretty big. I'd recommend making those smaller for bandwidth challenged people like me ^^.

**Comment by jo185** [comment]
Thanks for the feedback<3
I'll use responsive images to help out with lower bandwidth. And make it responsive for mobile devices.
As for the content, you probably didn't miss anything. At the moment these are all the pages. I am slowly adding content, whenever I have something new. I hope this is enough to be included in the ring. If not, please give me some advice and i'll create a new pull request later.

Happy new week.

**Comment by neauoire** [comment]
Feel free to open a new PR later, I'll close this one because it will probably create a conflict when if I accept another in the meantime. Good luck with your website, lemme know if you ever want to bounce some ideas :)

**Pull request closed without merging**
