### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by deuveir**
added personal wiki.

### CODE REVIEW

**Comment by neauoire** [comment]
Good to see you here osa <3
Let me know if you need help adding the ring icon to your site.

**Comment by deuveir** [comment]
I'll be rebuilding this website in the coming days. New design should have room for icons like that ^ _ ^

**Comment by neauoire** [comment]
Looking forward :)

**Comment by neauoire** [comment]
Let me know when the new design will be up :) I still don't see the icon in your footer. As much as possible, I would like the webring to be a two way street.

**Comment by deuveir** [comment]
i'll try getting it done this month! Will notify you when that happens.

**Comment by neauoire** [comment]
Looking forward :) Let me know if you need any JS help or wtvr. 
I'd be happy to help.

**Pull request merged**
