### PR TITLE
Added Opinionated Guides

### PR DESCRIPTION
**Pull request by VegaDeftwing**
Webring icon prominently displayed in the bottom left side of every page, in the footer.

The site is for hosting information for learning computer and electrical engineering, but may wind up containing multiple blog type posts from contributors in the future. Right now the site contains 3 pages of actual content, OpinionatedMusic, OpinionatedEngineering, and OpinionatedDesign. Of these, OpDesign is pracically empty at the moment while OpEng is already massive and OpMusic is growing rapidly.

Repo availabe at https://github.com/opinionatedguide/opinionatedguide.github.io-src . Just recently moved everything over to that repo and had to murder commit history in the process.

### CODE REVIEW

**Comment by neauoire** [comment]
Hey Vega I've been hoping you'd put something on the webring.

Your site [very much a work in progress](https://opinionatedguide.github.io/category/engineering.html#chapter-2-lets-do-it-then-installing-arch-linux) at the moment, so let's keep this open while you progress on building it up. I can check again in a few days to see how it has grown, in its current state it doesn't feel quite ready for the webring just yet.

**Comment by VegaDeftwing** [comment]
Yeah, I actually own deftwing.us (let's not talk about that site, it's a shitshow) but because I want to accept contributions easily running though github pages works fine and a lot of people know how it works annnddd it makes it feel like more of a community project, which is what I want even if as of now I've written everything there. Assuming I don't get distracted by building some eurorack modules ... today(? - it's 4am), I should be able to add around a dozen more pages to that site within 24 hours. Either way I'll comment here when it's a bit more fleshed out so you don't have to constantly check.

**Comment by neauoire** [comment]
I've merged your PR, your site well on its way :)

**Comment by ckipp01** [comment]
@VegaDeftwing hey! Are you by chance able to shoot in another PR to fill in the `author` key? If not, an author won't be able to be displayed for your posts in the hallway.

**Comment by VegaDeftwing** [comment]
huh, I didn't think about that. OpGuides is a bit weird for the webring in that it's supposed to be a community project instead of just me and as hallway isn't really built for that it's a weird consideration. On the other hand I am the lead maintainer and contributor and always will be, so I suppose I'll just submit a pull with myself as the author tomorrow morning if there are no objections.

**Pull request merged**
